// <auto-generated />
using System;
using GlobalSolution_MVC.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GlobalSolution_MVC.Migrations
{
    [DbContext(typeof(VisionaryBlueDbContext))]
    partial class VisionaryBlueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalSolution_MVC.Models.AutoridadeAmbiental", b =>
                {
                    b.Property<int>("AutoridadeAmbientalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_Autoridade");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoridadeAmbientalId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ds_autoridade_ambiental");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_autoridade_ambiental");

                    b.HasKey("AutoridadeAmbientalId");

                    b.ToTable("tb_autoridade_ambiental");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.AutoridadeAmbientalDenuncia", b =>
                {
                    b.Property<int>("AutoridadeDenunciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AutoridadeDenuncia");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoridadeDenunciaId"));

                    b.Property<int>("AutoridadeAmbientalId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DenunciaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("AutoridadeDenunciaId");

                    b.HasIndex("AutoridadeAmbientalId");

                    b.HasIndex("DenunciaId");

                    b.ToTable("tb_autoridade_ambiental_denuncia");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_Comentario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioId"));

                    b.Property<int?>("DenunciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ds_comentario");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("tp_comentario");

                    b.HasKey("ComentarioId");

                    b.HasIndex("DenunciaId");

                    b.ToTable("tb_comentario");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.Denuncia", b =>
                {
                    b.Property<int>("DenunciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_Denuncia");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DenunciaId"));

                    b.Property<int>("AutoridadeAmbientalId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_ocorrencia");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ds_denuncia");

                    b.Property<int>("LocalizacaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NotificacaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("st_denuncia");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("DenunciaId");

                    b.HasIndex("AutoridadeAmbientalId");

                    b.HasIndex("LocalizacaoId");

                    b.HasIndex("NotificacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tb_denuncia");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.Localizacao", b =>
                {
                    b.Property<int>("LocalizacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_Localizacao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizacaoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ds_localizacao");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("latitude");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("longitude");

                    b.HasKey("LocalizacaoId");

                    b.ToTable("tb_localizacao");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.Notificacao", b =>
                {
                    b.Property<int>("NotificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_Notificacao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacaoId"));

                    b.Property<int>("ComentarioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ds_comentario");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("st_comentario");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("tp_comentario");

                    b.HasKey("NotificacaoId");

                    b.HasIndex("ComentarioId");

                    b.ToTable("tb_notificacao");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.Residuo", b =>
                {
                    b.Property<int>("ResiduoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_Residuo");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResiduoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ds_residuo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("tp_residuo");

                    b.HasKey("ResiduoId");

                    b.ToTable("tb_residuo");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_Usuario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_usuario");

                    b.HasKey("UsuarioId");

                    b.ToTable("tb_usuario");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.AutoridadeAmbientalDenuncia", b =>
                {
                    b.HasOne("GlobalSolution_MVC.Models.AutoridadeAmbiental", "AutoridadeAmbiental")
                        .WithMany("Denuncias")
                        .HasForeignKey("AutoridadeAmbientalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalSolution_MVC.Models.Denuncia", "Denuncia")
                        .WithMany("Autoridades")
                        .HasForeignKey("DenunciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutoridadeAmbiental");

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.Comentario", b =>
                {
                    b.HasOne("GlobalSolution_MVC.Models.Denuncia", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("DenunciaId");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.Denuncia", b =>
                {
                    b.HasOne("GlobalSolution_MVC.Models.AutoridadeAmbiental", "AutoridadeAmbiental")
                        .WithMany()
                        .HasForeignKey("AutoridadeAmbientalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalSolution_MVC.Models.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalSolution_MVC.Models.Notificacao", "Notificacao")
                        .WithMany()
                        .HasForeignKey("NotificacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalSolution_MVC.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutoridadeAmbiental");

                    b.Navigation("Localizacao");

                    b.Navigation("Notificacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.Notificacao", b =>
                {
                    b.HasOne("GlobalSolution_MVC.Models.Comentario", "Comentario")
                        .WithMany()
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comentario");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.AutoridadeAmbiental", b =>
                {
                    b.Navigation("Denuncias");
                });

            modelBuilder.Entity("GlobalSolution_MVC.Models.Denuncia", b =>
                {
                    b.Navigation("Autoridades");

                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
